# Generated by Django 3.0.5 on 2024-07-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shop_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fn', models.CharField(max_length=30)),
                ('mb', models.IntegerField()),
                ('em', models.EmailField(max_length=254)),
                ('ps', models.CharField(max_length=30)),
                ('cps', models.CharField(max_length=30)),
            ],
        ),
    ]
