# Generated by Django 3.0.5 on 2024-07-29 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.FileField(upload_to='images')),
                ('br', models.CharField(max_length=50)),
                ('nm', models.CharField(max_length=100)),
                ('pr', models.IntegerField()),
                ('of', models.EmailField(max_length=254)),
                ('opr', models.IntegerField()),
            ],
        ),
    ]
