# Generated by Django 3.0.5 on 2024-07-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_data_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data_tbl',
            name='of',
            field=models.CharField(max_length=20),
        ),
    ]
