# Generated by Django 5.0.7 on 2024-07-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20240729_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('im', models.FileField(upload_to='images')),
                ('cg', models.CharField(max_length=50)),
                ('br', models.CharField(max_length=50)),
                ('nm', models.CharField(max_length=100)),
                ('pr', models.IntegerField()),
                ('of', models.CharField(max_length=20)),
                ('opr', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='data_tbl',
        ),
    ]
