# Generated by Django 5.0.6 on 2024-07-31 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_product_tbl_delete_data_tbl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tbl',
            name='of',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='cart_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shop_tbl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product_tbl')),
            ],
        ),
    ]
