# Generated by Django 5.0.7 on 2024-08-01 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_product_tbl_of_cart_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='wishlist_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shop_tbl')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product_tbl')),
            ],
        ),
    ]
