# Generated by Django 5.0.7 on 2024-08-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0006_wishlist_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='address_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('mob', models.IntegerField()),
                ('amb', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('st', models.CharField(max_length=30)),
                ('cty', models.CharField(max_length=30)),
                ('hs', models.CharField(max_length=50)),
                ('rd', models.CharField(max_length=50)),
            ],
        ),
    ]
