# Generated by Django 5.0.8 on 2024-08-07 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0007_address_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderstatus', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delivered', 'Delivered')], default='Pending', max_length=30)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.address_tbl')),
                ('cartproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.cart_tbl')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.shop_tbl')),
            ],
        ),
    ]
