# Generated by Django 3.0.7 on 2024-08-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0008_order_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vim', models.FileField(upload_to='images')),
                ('vn', models.CharField(max_length=30)),
                ('vpr', models.IntegerField()),
            ],
        ),
    ]
