# Generated by Django 3.0.7 on 2024-08-21 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_auto_20240821_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_tbl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.product_tbl')),
            ],
        ),
    ]
