# Generated by Django 5.1 on 2024-08-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_shop_tbl_city_shop_tbl_house_shop_tbl_pincode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_tbl',
            name='prc',
        ),
        migrations.DeleteModel(
            name='vehicle_tbl',
        ),
        migrations.DeleteModel(
            name='price_tbl',
        ),
    ]
