# Generated by Django 5.0.6 on 2024-09-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0013_remove_price_tbl_prc_delete_vehicle_tbl_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_tbl',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order_tbl',
            name='cartproduct',
        ),
        migrations.RemoveField(
            model_name='order_tbl',
            name='customer',
        ),
        migrations.AddField(
            model_name='order_tbl',
            name='city',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_tbl',
            name='hous',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_tbl',
            name='mob',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_tbl',
            name='nm',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_tbl',
            name='pin',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_tbl',
            name='road',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_tbl',
            name='stat',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_tbl',
            name='totalprice',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
