# Generated by Django 5.0.7 on 2024-09-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_alter_order_tbl_orderstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_tbl',
            name='totalprice',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
