# Generated by Django 5.0.7 on 2024-09-08 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0016_alter_order_tbl_totalprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_tbl',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selecteduserobjs', to='shopping.shop_tbl'),
        ),
        migrations.AlterField(
            model_name='order_tbl',
            name='orderstatus',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'paid'), ('delivered', 'delivered')], default='Pending', max_length=30),
        ),
    ]
